### ISSUE TITLE
contextual help opens in new tab

### ISSUE THREAD

**Issue by v4hn** [zhangfeiran/jupyterlab_pausable_contextual_help#1]
I tried running this extension with Jupyer Server 2.2.1.
When I press `<Ctrl>+i` with the extension installed it opens the contextual help in a new tab above the current window instead of next to the current window.

I believe this is not the intended behavior and not useful.

**Comment by zhangfeiran** [comment]
You can move the tab to the desired position manually, and it won't need to be done many times, since Jupyterlab can remember the tab position.

**Comment by v4hn** [comment]
Thanks for the fast reply!

That does indeed work somewhat, although it's clearly a workaround and the original contextual help shows up correctly without the plugin. :-)
Additionally, after I hide and later on show the help again with `<Ctrl>+i` the system resets the tab position, and the help does not update anymore (neither with autoupdate, nor with `F1`. This seems to be a related but probably orthogonal bug.

**Comment by zhangfeiran** [comment]
Ok, it turns out I missed one line of code when adapting the original one :)
Now the contextual help is opened right to the current tab, you can `pip install -U jupyterlab_pausable_contextual_help` and try out.

As for the second problem, I cannot reproduce this bug, maybe try refreshing the page?

**Comment by v4hn** [comment]
Thanks, just got around to test it and it works as expected.
I think I still get random hangs when I press `F1`, but I can't pinpoint an error condition right now and I'm not sure it's a problem with this plugin, specifically.
I will report back if I figure out an actual error condition.

Thanks for the plugin! :cat2:
